export const trainers = [
  {
    id: "1",
    name: "Amina Rahman",
    experience: 5,
    availableSlots: ["Friday", "Saturday", "Monday", "Wednesday"],
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    socials: {
      facebook: "https://facebook.com/amina",
      instagram: "https://instagram.com/amina",
      twitter: "https://twitter.com/amina",
    },
  },
  {
    id: "2",
    name: "Rafiq Ahmed",
    experience: 7,
    availableSlots: ["Tuesday", "Thursday", "Sunday"],
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    socials: {
      facebook: "https://facebook.com/rafiq",
      instagram: "https://instagram.com/rafiq",
      twitter: "https://twitter.com/rafiq",
    },
  },
  {
    id: "3",
    name: "Sadia Khan",
    experience: 4,
    availableSlots: ["Sunday", "Wednesday", "Friday", "Saturday", "Monday"],
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    socials: {
      facebook: "https://facebook.com/sadia",
      instagram: "https://instagram.com/sadia",
      twitter: "https://twitter.com/sadia",
    },
  },
  {
    id: "4",
    name: "Tanvir Islam",
    experience: 6,
    availableSlots: ["Monday", "Tuesday", "Saturday"],
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    socials: {
      facebook: "https://facebook.com/tanvir",
      instagram: "https://instagram.com/tanvir",
      twitter: "https://twitter.com/tanvir",
    },
  },
  {
    id: "5",
    name: "Nusrat Jahan",
    experience: 3,
    availableSlots: ["Thursday", "Friday", "Sunday"],
    image: "https://randomuser.me/api/portraits/women/23.jpg",
    socials: {
      facebook: "https://facebook.com/nusrat",
      instagram: "https://instagram.com/nusrat",
      twitter: "https://twitter.com/nusrat",
    },
  },
  {
    id: "6",
    name: "Arif Chowdhury",
    experience: 8,
    availableSlots: ["Wednesday", "Friday", "Saturday", "Sunday"],
    image: "https://randomuser.me/api/portraits/men/61.jpg",
    socials: {
      facebook: "https://facebook.com/arif",
      instagram: "https://instagram.com/arif",
      twitter: "https://twitter.com/arif",
    },
  },
  {
    id: "7",
    name: "Mitu Sultana",
    experience: 2,
    availableSlots: ["Monday", "Tuesday", "Thursday"],
    image: "https://randomuser.me/api/portraits/women/42.jpg",
    socials: {
      facebook: "https://facebook.com/mitu",
      instagram: "https://instagram.com/mitu",
      twitter: "https://twitter.com/mitu",
    },
  },
  {
    id: "8",
    name: "Shahriar Kabir",
    experience: 9,
    availableSlots: ["Friday", "Saturday", "Sunday", "Tuesday"],
    image: "https://randomuser.me/api/portraits/men/72.jpg",
    socials: {
      facebook: "https://facebook.com/shahriar",
      instagram: "https://instagram.com/shahriar",
      twitter: "https://twitter.com/shahriar",
    },
  },
  {
    id: "9",
    name: "Lubna Haque",
    experience: 4,
    availableSlots: ["Saturday", "Monday", "Wednesday"],
    image: "https://randomuser.me/api/portraits/women/90.jpg",
    socials: {
      facebook: "https://facebook.com/lubna",
      instagram: "https://instagram.com/lubna",
      twitter: "https://twitter.com/lubna",
    },
  },
  {
    id: "10",
    name: "Fahim Hasan",
    experience: 6,
    availableSlots: ["Tuesday", "Thursday", "Friday", "Sunday"],
    image: "https://randomuser.me/api/portraits/men/38.jpg",
    socials: {
      facebook: "https://facebook.com/fahim",
      instagram: "https://instagram.com/fahim",
      twitter: "https://twitter.com/fahim",
    },
  },
  {
    id: "11",
    name: "Moushumi Akter",
    experience: 3,
    availableSlots: ["Wednesday", "Friday", "Saturday"],
    image: "https://randomuser.me/api/portraits/women/58.jpg",
    socials: {
      facebook: "https://facebook.com/moushumi",
      instagram: "https://instagram.com/moushumi",
      twitter: "https://twitter.com/moushumi",
    },
  },
  {
    id: "12",
    name: "Imran Hossain",
    experience: 10,
    availableSlots: ["Monday", "Tuesday", "Thursday", "Saturday", "Sunday"],
    image: "https://randomuser.me/api/portraits/men/87.jpg",
    socials: {
      facebook: "https://facebook.com/imran",
      instagram: "https://instagram.com/imran",
      twitter: "https://twitter.com/imran",
    },
  },
];

